### ISSUE TITLE
[BUG] move demo scenes to another folder will break the project

### ISSUE THREAD

**Issue by JustusPan** [maktoobgar/scene_manager#14] opened 2023-10-04 08:56 UTC
v3.6.0
Godot:4.1.1
if we move all files inside the `demo` folder to other folder whose path is `addons_demos/scene_manager/`, follow error will be printed if run scene1 test.
`Scene Manager Error: loaded scene is not defined in scene manager tool.`

**Comment by maktoobgar** [comment] 2023-10-04 14:41
Hello.
This is not a bug, this is a custom error that I am giving to you.

## Describing

You need to have all incoming and current scenes defined with their addresses and accessible with just a key in scene_manager because scene_manager is tracking your steps to be able to go back to any other steps that is needed but if it can not find the scene that you currently have or the scene which you desire to switch to, it will give you this custom error that I'm the guy who generated it as I said before.

## Fix

And finally long story short, to fix this:
1. go to **Scene Manager** tab on the editor.
2. Click refresh and then click save.
3. It is done and you should be good to go.

### Finally

I close this issue for now but if the same problem happens again, after the fix, inform me and I can work on that matter and fix why it is not saving the scenes.

**Closed by maktoobgar** 2023-10-04 14:41 UTC

**Comment by JustusPan** [comment] 2023-10-05 03:14
Refresh & save method works well today. but the exactly same method didn't work when I create this issue

**Comment by maktoobgar** [comment] 2023-10-05 05:45
> Refresh & save method works well today. but the exactly same method didn't work when I create this issue

Please inform me if that happens again.
