### ISSUE TITLE
Crashing on Scene changes in build, but going into build and hitting Save fixes it?

### ISSUE THREAD

**Issue by Bonkahe** [maktoobgar/scene_manager#3] opened 2023-01-25 19:03 UTC
So, I made a game jam game over the last week, and in the build when transitioning from a game level to another game level, or to a death screen, but it does not occur when transitioning from the main menu to the level scene, or vice versa, but when transitioning to the death scene. I went back in and hit save on the Scene Manager and it resolved this, even though no scene changes were made. Not sure what is going on, but I uploaded to github BEFORE hitting save, so theoretically if you download the source, and hit export, and export it to windows it SHOULD break when you die in game.

I know this is not exactly an issue, per say, it could be if I didn't resolve it, but I wanted to let you know so you could resolve it if you are able.

Repo:
[https://github.com/Bonkahe/WildJam53-Pattern-Blue](https://github.com/Bonkahe/WildJam53-Pattern-Blue)

Be advised; I built it with Godot 4 Beta 11-mono, entirely unsure if it will occur in other versions.

If you want to go ahead and hit resolved on this, and just use it as a source of info, that's perfect. 
Thank you for the addon regardless, it's excellent and does exactly what I need it to do.

**Comment by maktoobgar** [comment] 2023-01-26 12:08
First let me tell you, I'm too happy that this addon is actually being used and this is literally the best news.
Then let me thank you for submitting an issue.

And about the issue, let me ask a question:
Does this situation just happen on windows? (Mainly asked because you mentioned: "export it to **windows** it SHOULD break when you die in game.").
I'm gonna try this on [godot4-beta15](https://downloads.tuxfamily.org/godotengine/4.0/beta15/).(Just for mainly less bugs) There is a high chance this is just a bug on godot4-beta11 because transition between different scenes by SceneManager node does not break your game, it either changes the scene or it does nothing.
And in the end, the Linux output version of the game works just fine in described scenario.
I'm gonna switch to windows(I'm on Linux at the time) to test it out.
Will be back in a couple of minutes.

**Comment by maktoobgar** [comment] 2023-01-26 13:13
I'm back.
It seems to be a problem with Windows version of your game cause the Linux one is fine in `game` to `menu` transition scenario.

I couldn't build your project cause it was mono version of godot and I really don't have time to setup `.net` and deal with `C#` so please update your godot4 version to [godot4-beta15](https://downloads.tuxfamily.org/godotengine/4.0/beta15/) and then build and test it out again and if still the problem existed, I personally still don't think this is a problem with this addon because Linux version of the game seems to function just fine but I'm gonna keep this issue open just in case if something new proves that I'm wrong as hell.
Keep me updated please.

Have a good day.

**Comment by maktoobgar** [comment] 2023-01-27 07:05
So it seems that the problem is fixed.
I'm gonna close this issue now.

If you see any other bug or odd behavior, I'll be thankful for an issue so that SceneManager can get better and more stable.
If you thought of some new features, I'll be happy to hear that too because at this point I think SceneManager can not get any better just because I'm fully out of ideas.

Farewell.

**Closed by maktoobgar** 2023-01-27 07:05 UTC
